---
- name: Listen for events on a webhook
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Fire on events from supported OS
      condition: event.payload.os == "ios"
      action:
        run_job_template:
          name: Standard network configuration
          organization: Network
          job_args:
            limit: "{{ event.payload.host }}"
